// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: init_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInitialConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VersionTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=versionTimestamp,proto3,oneof" json:"versionTimestamp,omitempty"`
}

func (x *GetInitialConfigRequest) Reset() {
	*x = GetInitialConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_init_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInitialConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInitialConfigRequest) ProtoMessage() {}

func (x *GetInitialConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_init_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInitialConfigRequest.ProtoReflect.Descriptor instead.
func (*GetInitialConfigRequest) Descriptor() ([]byte, []int) {
	return file_init_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetInitialConfigRequest) GetVersionTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.VersionTimestamp
	}
	return nil
}

type GetInitialConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LatestURLs *URLsList `protobuf:"bytes,1,opt,name=latestURLs,proto3,oneof" json:"latestURLs,omitempty"`
}

func (x *GetInitialConfigResponse) Reset() {
	*x = GetInitialConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_init_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInitialConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInitialConfigResponse) ProtoMessage() {}

func (x *GetInitialConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_init_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInitialConfigResponse.ProtoReflect.Descriptor instead.
func (*GetInitialConfigResponse) Descriptor() ([]byte, []int) {
	return file_init_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetInitialConfigResponse) GetLatestURLs() *URLsList {
	if x != nil {
		return x.LatestURLs
	}
	return nil
}

type URLsList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VersionTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=versionTimestamp,proto3" json:"versionTimestamp,omitempty"`
	SupabaseURL      string                 `protobuf:"bytes,2,opt,name=supabaseURL,proto3" json:"supabaseURL,omitempty"`
	SupabaseKey      string                 `protobuf:"bytes,3,opt,name=supabaseKey,proto3" json:"supabaseKey,omitempty"`
}

func (x *URLsList) Reset() {
	*x = URLsList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_init_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLsList) ProtoMessage() {}

func (x *URLsList) ProtoReflect() protoreflect.Message {
	mi := &file_init_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLsList.ProtoReflect.Descriptor instead.
func (*URLsList) Descriptor() ([]byte, []int) {
	return file_init_service_proto_rawDescGZIP(), []int{2}
}

func (x *URLsList) GetVersionTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.VersionTimestamp
	}
	return nil
}

func (x *URLsList) GetSupabaseURL() string {
	if x != nil {
		return x.SupabaseURL
	}
	return ""
}

func (x *URLsList) GetSupabaseKey() string {
	if x != nil {
		return x.SupabaseKey
	}
	return ""
}

var File_init_service_proto protoreflect.FileDescriptor

var file_init_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x69, 0x74,
	0x69, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x4b, 0x0a, 0x10, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x10, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x88, 0x01, 0x01, 0x42, 0x13, 0x0a,
	0x11, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0x59, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e,
	0x0a, 0x0a, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x55, 0x52, 0x4c, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x0a, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x88, 0x01, 0x01, 0x42, 0x0d,
	0x0a, 0x0b, 0x5f, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x22, 0x96, 0x01,
	0x0a, 0x08, 0x55, 0x52, 0x4c, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x46, 0x0a, 0x10, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x10, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x75, 0x70, 0x61, 0x62, 0x61, 0x73, 0x65, 0x55, 0x52,
	0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x75, 0x70, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x55, 0x52, 0x4c, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x75, 0x70, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x75, 0x70, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x32, 0x56, 0x0a, 0x0b, 0x49, 0x6e, 0x69, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x69, 0x74,
	0x69, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x49,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x10,
	0x5a, 0x0e, 0x69, 0x6e, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_init_service_proto_rawDescOnce sync.Once
	file_init_service_proto_rawDescData = file_init_service_proto_rawDesc
)

func file_init_service_proto_rawDescGZIP() []byte {
	file_init_service_proto_rawDescOnce.Do(func() {
		file_init_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_init_service_proto_rawDescData)
	})
	return file_init_service_proto_rawDescData
}

var file_init_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_init_service_proto_goTypes = []interface{}{
	(*GetInitialConfigRequest)(nil),  // 0: GetInitialConfigRequest
	(*GetInitialConfigResponse)(nil), // 1: GetInitialConfigResponse
	(*URLsList)(nil),                 // 2: URLsList
	(*timestamppb.Timestamp)(nil),    // 3: google.protobuf.Timestamp
}
var file_init_service_proto_depIdxs = []int32{
	3, // 0: GetInitialConfigRequest.versionTimestamp:type_name -> google.protobuf.Timestamp
	2, // 1: GetInitialConfigResponse.latestURLs:type_name -> URLsList
	3, // 2: URLsList.versionTimestamp:type_name -> google.protobuf.Timestamp
	0, // 3: InitService.GetInitialConfig:input_type -> GetInitialConfigRequest
	1, // 4: InitService.GetInitialConfig:output_type -> GetInitialConfigResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_init_service_proto_init() }
func file_init_service_proto_init() {
	if File_init_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_init_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInitialConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_init_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInitialConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_init_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URLsList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_init_service_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_init_service_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_init_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_init_service_proto_goTypes,
		DependencyIndexes: file_init_service_proto_depIdxs,
		MessageInfos:      file_init_service_proto_msgTypes,
	}.Build()
	File_init_service_proto = out.File
	file_init_service_proto_rawDesc = nil
	file_init_service_proto_goTypes = nil
	file_init_service_proto_depIdxs = nil
}
